# Generated by Django 6.0.2 on 2026-02-25 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=35)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('especialidad', models.CharField(max_length=35)),
                ('matricula', models.CharField(max_length=25)),
                ('inicio_jornada', models.TimeField(verbose_name='Hora de inicio')),
                ('fin_jornada', models.TimeField(verbose_name='Hora fin de jornada')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=35)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('historia_clinica', models.TextField()),
                ('posee_obra_social', models.BooleanField()),
                ('obra_social', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('duracion_minutos', models.IntegerField(default=30, verbose_name='duracion del turno')),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('atendido', 'Atendido')], default='confirmado', max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='agenda.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='agenda.paciente')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
    ]
