# Generated by Django 6.0.2 on 2026-03-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_medico_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='hora_resumen_diario',
            field=models.TimeField(default='08:00', help_text='Hora que el medico recibe su agenda del dia', verbose_name='Hora de resumen diario'),
        ),
        migrations.AddField(
            model_name='medico',
            name='horas_recordatorio_paciente',
            field=models.IntegerField(default=24, help_text='Horas antes del turno avisar al paciente', verbose_name='Recordatorio al paciente (horas antes)'),
        ),
        migrations.AddField(
            model_name='medico',
            name='notificaciones_activas',
            field=models.BooleanField(default=True, help_text='Si es False, no se envia mail', verbose_name='Notificaciones activas'),
        ),
    ]
