# Generated by Django 6.0.2 on 2026-02-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_disponibilidadsemanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('PR', 'Programado'), ('AS', 'Asistido'), ('CA', 'Cancelado'), ('AU', 'Ausente')], default='PR', max_length=2),
        ),
    ]
