# Generated by Django 6.0.2 on 2026-03-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_alter_turno_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='tiempo_consulta',
            field=models.PositiveIntegerField(default=30, verbose_name='Duracion de consulta (minutos)'),
        ),
    ]
