# Generated by Django 6.0.2 on 2026-09-07 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_tokenverificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='hora_resumen_diario',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Hora que el medico recibe su agenda del dia', verbose_name='Hora de resumen diario'),
        ),
    ]
