# Generated by Django 6.0.2 on 2026-03-01 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_medico_tiempo_consulta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='agenda.medico')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('medico', 'fecha', 'hora_inicio')},
            },
        ),
    ]
