# Generated by Django 6.0.2 on 2026-03-02 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='agenda.slot'),
        ),
    ]
