# Generated by Django 6.0.2 on 2026-03-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_turno_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['slot__fecha', 'slot__hora_inicio']},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='duracion_minutos',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha_hora',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='medico',
        ),
        migrations.AlterField(
            model_name='turno',
            name='slot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='agenda.slot'),
            preserve_default=False,
        ),
    ]
