# Generated by Django 6.0.2 on 2026-03-02 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_alter_turno_options_remove_turno_duracion_minutos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='turno', to='agenda.slot'),
        ),
    ]
